//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by visamp.rc
//
#define IDD_MAINDIALOG                  101
#define IDI_ICON1                       102
#define IDC_QUIT                        1000
#define IDC_LOAD_SAMPLE                 1004
#define IDC_FREE_SAMPLE                 1005
#define IDC_PLAY_LEFT_SAMPLE            1006
#define IDC_LOAD_PRESET                 1008
#define IDC_FREE_PRESET                 1009
#define IDC_NOTE_ON                     1010
#define IDC_NOTE_OFF                    1011
#define IDC_PLAY_RIGHT_SAMPLE           1013
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
