/*****************************************************************************
*                                                                            *
* RESOURCE.H WINAWE32 Resource header file                                   *
*                                                                            *
* (C) Copyright Creative Technology Ltd. 1992-94. All rights reserved        *
* worldwide.                                                                 *
*                                                                            *
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY      *
* KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE        *
* IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR      *
* PURPOSE.                                                                   *
*                                                                            *
* You have a royalty-free right to use, modify, reproduce and                *
* distribute the Sample Files (and/or any modified version) in               *
* any way you find useful, provided that you agree to                        *
* the Creative's Software Licensing Aggreement and you also agree that       *
* Creative has no warranty obligations or liability for any Sample Files.    *
*                                                                            *
******************************************************************************/

/*****************************************************************************
*   File name   : RESOURCE.H                                                 *
*                                                                            *
*   Programmer  : Cheng Kok Hoong                                            *
*                 Creative Technology Ltd, 1994. All rights reserved.        *
*                                                                            *
*   WINAWE32 Resource header file                                            *
*                                                                            *
******************************************************************************/

#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define ID_FILE_OPEN                    134
#define ID_STOP_MIDI                    159
#define ID_QUIT                         136
#define ID_SETTINGS_REVERB_ROOM1        138
#define ID_SETTINGS_REVERB_ROOM2        139
#define ID_SETTINGS_REVERB_ROOM3        140
#define ID_SETTINGS_REVERB_HALL1        141
#define ID_SETTINGS_REVERB_HALL2        142
#define ID_SETTINGS_REVERB_PLATE        143
#define ID_SETTINGS_REVERB_DELAY        144
#define ID_SETTINGS_REVERB_PANNINGDELAY 145
#define ID_SETTINGS_CHORUS_CHORUS1      147
#define ID_SETTINGS_CHORUS_CHORUS2      148
#define ID_SETTINGS_CHORUS_CHORUS3      149
#define ID_SETTINGS_CHORUS_CHORUS4      150
#define ID_SETTINGS_CHORUS_FEEBACKCHORUS 151
#define ID_SETTINGS_CHORUS_FLANGER      152
#define ID_SETTINGS_CHORUS_SHORTDELAY   153
#define ID_SETTINGS_CHORUS_SHORTDELAYFB 154
#define ID_MISC_SYNTHBANK_GM            125
#define ID_MISC_SYNTHBANK_GS            126
#define ID_MISC_SYNTHBANK_MT32          127
#define ID_LOAD_USERBANK                158
#define ID_CLEAR_BANK                   160
#define ID_SETTINGS_TRIGGERME           156
#define ID_GUI_CONTROLPANEL             120
#define ID_GUI_CONTROLLER               121
#define ID_QUERY_DRAM                   133
#define ID_QUERY_SYNTH                  155
#define IDM_ABOUT                       100
#define IDC_BIGOFF                      1000
#define IDC_BIGON                       1001
#define IDC_SETPATCH                    1002
#define IDC_PC                          1003
#define IDC_SETMIDI                     1004
#define IDC_MIDI                        1005
#define IDC_STATIC                      -1
